### ISSUE TITLE
remove alignments from GFE database

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/gfe-db#51]
Remove ProteinAlignment, GenomicAlignment, NucleotideAlginment from the model.
Currently they can change between IPD/IMGT-HLADB releases even if the sequences doesn't change.
Modeling this in GFEDB is hard and **there is no use case.** and the alignments are useless without the metadata.

It also takes up a lot of space.

**Comment by abk7777** [comment]
Alignments are removed in the current schema. To remove alignments pass `ALIGN=FALSE` to the StepFunctions input:
```json
{
  "params": {
    "environment": {
      "RELEASES": "3430",
      "ALIGN": "False",
      "KIR": "False",
      "MEM_PROFILE": "False",
      "LIMIT": ""
    }
  }
}
```
