### ISSUE TITLE
DNS configuration for deployment

### ISSUE THREAD

**Issue by chrisammon3000** [nmdp-bioinformatics/gfe-db#67]
## Description
A stable version of gfe-db can be deployed and hosted using Elastic IP which works for development and testing, but a production deployment requires DNS hosting, HTTPS and SSL. There are some bugs and/or missing functionality in #66 that preventa custom DNS configuration to be deployed.

## Discussion
gfe-db can be hosted in two ways:
1) Elastic IP, appropriate for a development release
2) Custom domain, appropriate for a production deployment

The easiest way to achieve this is probably to use two separate templates for the base infrastructure layer, one that deploys resources for Elastic IP and one that deploys resources for a custom domain.

## Tasks
_TBD_

**Comment by abk7777** [comment]
@pbashyal-nmdp
